AWSTemplateFormatVersion: "2010-09-09"
Description: Sample VPC CloudFormation
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      Tags:
        - Key: Name
          Value: SampleVPC
