AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Organizations - Organizational Units Setup

Parameters:
  RootOrgId:
    Type: String
    Description: The Root Organization ID (e.g., r-xxxx)

Resources:
  # Security OU
  SecurityOU:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Security
      ParentId: !Ref RootOrgId

  # Sandbox OU
  SandboxOU:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Sandbox
      ParentId: !Ref RootOrgId

  # Workloads OU
  WorkloadsOU:
    Type: AWS::Organizations::OrganizationalUnit
    Properties:
      Name: Workloads
      ParentId: !Ref RootOrgId

Outputs:
  SecurityOUId:
    Description: Security OU ID
    Value: !Ref SecurityOU

  SandboxOUId:
    Description: Sandbox OU ID
    Value: !Ref SandboxOU

  WorkloadsOUId:
    Description: Workloads OU ID
    Value: !Ref WorkloadsOU
