name: Deploy VPC

on:
  workflow_dispatch:

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::186582696292:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Validate VPC Template
        run: |
          echo "Validating VPC Template..."
          aws cloudformation validate-template \
            --template-body file://infra/networking/vpc-stack.yaml

      - name: Deploy VPC Stack (Debug Mode)
        run: |
          set -x  # Enable shell debugging
          echo "Deploying VPC Stack..."
          aws cloudformation deploy \
            --template-file infra/networking/vpc-stack.yaml \
            --stack-name lz-vpc-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides VpcCIDR=10.0.0.0/16 || {
                echo "❌ Deployment failed! Fetching stack events..."
                aws cloudformation describe-stack-events --stack-name lz-vpc-stack
                exit 1
          }
