name: Deploy SCP Policies

on:
  workflow_dispatch:

jobs:
  deploy-scp:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::186582696292:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Deploy SCP Stack
        run: |
          aws cloudformation deploy \
            --stack-name lz-scp-stack \
            --template-file infra/scp/scp-policies.yaml \
            --parameter-overrides file://infra/scp/parameters.json \
            --capabilities CAPABILITY_NAMED_IAM
