name: Deploy Organizational Units

on:
  workflow_dispatch:

jobs:
  deploy-ou:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::186582696292:role/GitHubActionsOIDCRole
          aws-region: us-east-1
     
     - name: Deploy Organizational Units Stack
       run: |
         aws cloudformation deploy \
           --stack-name lz-organizational-units \
           --template-file infra/organizations/organizational-units.yaml \
           --capabilities CAPABILITY_NAMED_IAM \
           --role-arn aarn:aws:iam::186582696292:role/CloudFormationExecutionRole \
           --parameter-overrides RootOrgId=$ROOT_ID