name: Deploy VPC

on:
  workflow_dispatch:

jobs:
  deploy-vpc:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::186582696292:role/GitHubActionsOIDCRole
          aws-region: us-east-1

      - name: Deploy VPC Stack
        run: |
          aws cloudformation deploy \
            --template-file infra/networking/vpc-stack.yaml \
            --stack-name lz-vpc-stack \
            --capabilities CAPABILITY_NAMED_IAM
